baseURL = "https://sahilagnihotri.github.io/"
languageCode = "en-us"
title = "sahilagnihotri github pages site"
theme = "hugo-xmin"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Sahil Agnihotri"
  description = "A minimal Hugo site using the XMin theme."
  github = "https://github.com/sahilagnihotri"
  linkedin = "https://linkedin.com/in/sahilagnihotri"
  twitter = "https://twitter.com/sahilagnihotri"

[permalinks]
  note = "/note/:year/:month/:day/:slug/"
  post = "/post/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Assignments"
    url = "/assignments"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3